import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

function DownloadReport({ data }) {
  const generatePDF = () => {
    if (!data) return;

    const doc = new jsPDF();

    const confidence = Number(data.confidence).toFixed(2);

    let threat = "LOW";
    if (confidence >= 80) threat = "CRITICAL";
    else if (confidence >= 60) threat = "HIGH";
    else if (confidence >= 30) threat = "MEDIUM";

    // ==========================
    // Title
    // ==========================

    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);
    doc.text("AEGIS-NSAI", 14, 20);

    doc.setFontSize(13);
    doc.setFont("helvetica", "normal");
    doc.text(
      "Neuro-Symbolic Intrusion Detection Report",
      14,
      30
    );

    doc.setFontSize(10);
    doc.text(
      "CSV Network Analysis",
      14,
      36
    );

    // ==========================
    // Metadata
    // ==========================

    doc.text(
      `Generated : ${new Date().toLocaleString()}`,
      14,
      44
    );

    doc.text(
      `Report ID : AEG-${Date.now()}`,
      130,
      44
    );

    // ==========================
    // Summary
    // ==========================

    autoTable(doc, {
      startY: 52,
      head: [["Field", "Value"]],
      body: [
        ["Final Prediction", data.prediction],
        ["Confidence", `${confidence}%`],
        ["Threat Level", threat],
        ["ML Prediction", data.ml_prediction || data.mlPrediction || "N/A"],
        [
          "Symbolic Prediction",
          data.symbolic_prediction ||
            data.symbolicPrediction ||
            "N/A",
        ],
      ],
      headStyles: {
        fillColor: [34, 197, 94],
      },
    });

    // ==========================
    // AI Explanation
    // ==========================

    let y = doc.lastAutoTable.finalY + 15;

    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("AI Explanation", 14, y);

    y += 8;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);

    const message = data.message || "No explanation available.";

    const explanationLines = doc.splitTextToSize(
      message,
      180
    );

    doc.text(explanationLines, 14, y);

    y += explanationLines.length * 6 + 12;

    // ==========================
    // Knowledge Graph
    // ==========================

    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);

    doc.text("Knowledge Graph", 14, y);

    y += 10;

    autoTable(doc, {
      startY: y,
      head: [["Related Indicators"]],
      body:
        (data.knowledge_graph || []).length > 0
          ? data.knowledge_graph.map((item) => [item])
          : [["No related indicators available"]],
      headStyles: {
        fillColor: [30, 30, 30],
      },
    });

    // ==========================
    // Footer
    // ==========================

    doc.setFontSize(10);

    doc.text(
      "Generated by AEGIS-NSAI • Neuro-Symbolic Intrusion Detection System",
      14,
      285
    );

    doc.save("AEGIS-NSAI-Report.pdf");
  };

  return (
    <div
      className="info-card"
      style={{ textAlign: "center" }}
    >
      <h3>Export Report</h3>

      <p
        style={{
          color: "#9ca3af",
          marginTop: "10px",
          marginBottom: "20px",
        }}
      >
        Download a professional PDF analysis report.
      </p>

      <button
        onClick={generatePDF}
        style={{
          padding: "14px 30px",
          border: "none",
          borderRadius: "10px",
          background: "#22c55e",
          color: "#fff",
          fontWeight: "700",
          fontSize: "16px",
          cursor: "pointer",
        }}
      >
        Download PDF Report
      </button>
    </div>
  );
}

export default DownloadReport;